#!/bin/bash

export PATH=$HOME/.config/bspwm:$HOME/bin:$PATH
export SCREENS=$(xrandr -q | grep " connected" | wc -l)

ROMAN=(I II III IV V VI VII VIII IX X)
SPLIT=$((10 / SCREENS))
for (( s = 0; s < ${SCREENS}; s++ )); do
    bspc monitor ^$((s + 1)) -d ${ROMAN[$((s * SPLIT))]}
    for (( m = 1; m < ${SPLIT} ; m++ )); do
	    bspc monitor ^$((s + 1)) -a ${ROMAN[$((s * SPLIT + m))]}
    done
done

bspc config split_ratio                 0.52
bspc config focused_border_color        "#009000"
bspc config active_border_color         "#007000"
bspc config normal_border_color         "#004000"
bspc config focused_locked_border_color "#000090"
bspc config active_locked_border_color  "#000070"
bspc config normal_locked_border_color  "#000040"
bspc config urgent_border_color         "#700000"
bspc config border_width                1
bspc config window_gap                  8
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config apply_floating_atom         true
bspc config focus_follows_pointer       true
bspc config top_padding                 18

bspc config rule_command "$(which rule_command)"

rulc -a 'class=="Gimp"' 'desktop=^8 follow=on floating=on'
rulc -a 'class=="Chromium"' 'desktop=^2'
rulc -a 'instance=="mpv"' 'floating=on'
rulc -a 'class=="Kupfer.py"' 'focus=on'
rulc -a 'class=="Screenkey"' 'manage=off'

killall -9 panel

panel bar &
