#!/bin/sh

export PATH=$HOME/.config/bspwm:$PATH

FIRST_DESK=1
REMAINING_DESKS="$(seq 2 9) 0"
bspc desktop Desktop01 -n $FIRST_DESK
bspc monitor -a $REMAINING_DESKS
bspc monitor -p 16 0 0 0

bspc rule -a Gimp --floating
bspc rule -a mplayer-float --floating

bspc config split_ratio                 0.52
bspc config focused_border_color        "#009000"
bspc config active_border_color         "#007000"
bspc config normal_border_color         "#004000"
bspc config focused_locked_border_color "#000090"
bspc config active_locked_border_color  "#000070"
bspc config normal_locked_border_color  "#000040"
bspc config urgent_border_color         "#700000"
bspc config border_width                1
bspc config window_gap                  8
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config apply_floating_atom         true
bspc config focus_follows_pointer       true

killall -9 panel

panel bar &
