#!/bin/sh
#
# Raedwulf's bar configuration

while read -r line ; do
    case $line in
        C*)
            clock_info="${line#?}\\fr"
            ;;
        B*)
            bat_info="${line#?}\\fr"
            ;;
	P*)
            cpu_info="${line#?}\\fr"
            ;;
	H*)
            thermal_info="${line#?}\\fr"
            ;;
	M*)
            mem_info="${line#?}\\fr"
            ;;
	N*)
            wifi_info="${line#?}\\fr"
            ;;
	D*)
            disk_info="${line#?}\\fr"
            ;;
        T*)
            title="${line#?}"
            ;;
        W*)
            wm_infos=""
            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                case $item in
                    [OFU]*)
                        # active desktop
                        wm_infos="$wm_infos\\b5\\u7 \\f0${name}\\fr"
                        ;;
                    o*)
                        # inactive but occupied desktop
                        wm_infos="$wm_infos \\ur\\br${name}"
                        ;;
                    f*)
                        # inactive desktop
                        wm_infos="$wm_infos \\ur\\br\\f7${name}\\fr"
                        ;;
                    u*)
                        # urgent desktop
                        wm_infos="$wm_infos \\ur\\b9\\f0${name}\\fr\\br"
                        ;;
                    L*)
                        # layout
                        layout=$(printf "%s" "${name}" | sed 's/\(.\).*/\U\1/')
                        wm_infos="$wm_infos \\ur\\b4\\f0$layout\\br\\fr"
                        ;;
                esac
                shift
            done
            ;;
    esac
    printf "%s\n" "$wm_infos        $title\\r$cpu_info|$thermal_info|$disk_info|$mem_info|$bat_info|$wifi_info|$clock_info"
done
