#!/bin/bash
#
# Raedwulf's bar configuration

SCREENS=$(xrandr -q | grep " connected" | wc -l)
while read -r line ; do
    case $line in
        C*)
            clock_info="${line#?}\\fr"
            ;;
        B*)
            bat_info="${line#?}\\fr"
            ;;
        P*)
            cpu_info="${line#?}\\fr"
            ;;
        H*)
            thermal_info="${line#?}\\fr"
            ;;
        M*)
            mem_info="${line#?}\\fr"
            ;;
        N*)
            wifi_info="${line#?}\\fr"
            ;;
        D*)
            disk_info="${line#?}\\fr"
            ;;
        T*)
            title="${line#?}"
            ;;
        W*)
            wm_infos=""
            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                case $item in
                    O*)
                        # focused occupied desktop
                        wm_infos="$wm_infos \\u3\\br\\fr${name}\\ur"
                        ;;
                    F*)
                        # focused free desktop
                        wm_infos="$wm_infos \\u4\\br\\f7${name}\\ur"
                        ;;
                    U*)
                        # focused urgent desktop
                        wm_infos="$wm_infos \\u9\\br\\fr${name}\\ur"
                        ;;
                    o*)
                        # occupied desktop
                        wm_infos="$wm_infos \\br\\fr${name}"
                        ;;
                    f*)
                        # free desktop
                        wm_infos="$wm_infos \\br\\f7${name}"
                        ;;
                    u*)
                        # urgent desktop
                        wm_infos="$wm_infos \\b1\\fr${name}"
                        ;;
                    L*)
                        # layout
                        layout=$(printf "%s" "${name}" | sed 's/\(.\).*/\U\1/')
                        wm_infos="$wm_infos    \\br\\f6$layout"
                        ;;
                esac
                shift
            done
            ;;
    esac
    TEXT="$wm_infos        $title\\r$cpu_info|$thermal_info|$disk_info|$mem_info|$bat_info|$wifi_info|$clock_info"
    for (( s = 0; s < ${SCREENS}; s++ )); do
        printf "\\s%1d%s" "${s}" "${TEXT}"
    done
    echo
    echo "${NUM}" >> /tmp/asdf2
done
