#! /bin/sh
#
# Raedwulf's bar configuration

while read -r line ; do
    case $line in
        C*)
            clock_info="\\f5${line#?}\\fr"
            ;;
        B*)
            bat_info="\\f5${line#?}\\fr"
            ;;
        T*)
            title="${line#?}"
            ;;
        W*)
            wm_infos=""
            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                case $item in
                    u*)
                        # urgent desktop
                        wm_infos="$wm_infos \\b3\\f0${name}\\fr\\br"
                        ;;
                    [DU]*)
                        # active desktop
                        wm_infos="$wm_infos \\u5\\b2\\f9${name}\\fr\\br\\ur"
                        ;;
                    d*)
                        # inactive but occupied desktop
                        wm_infos="$wm_infos \\f7${name}\\fr"
                        ;;
                    E*)
                        # inactive desktop
                        wm_infos="$wm_infos ${name}"
                        ;;
                    L*)
                        # layout
                        layout=$(printf "%s" "${name}" | sed 's/\(.\).*/\U\1/')
                        wm_infos="$wm_infos \\b4\\f0$layout\\br\\fr"
                        ;;
                esac
                shift
            done
            ;;
    esac
    echo "$wm_infos $title $bat_info $sys_infos" >> /tmp/blargh
    printf "%s\n" "$wm_infos\\c$title\\r$bat_info $clock_info"
done
