#! /bin/sh

flavor=${1:-bar}

bspc control --put-status
xtitle -sf 'T%s' > "$PANEL_FIFO" &
clock -sf 'C%c' -i 1 > "$PANEL_FIFO" &
battery -sf'B%s %d' -i 5 > $PANEL_FIFO &
case "$flavor" in
    bar)
        cat "$PANEL_FIFO" | panel_bar | bar-aint-recursive
        ;;
    dzen2)
        . panel_colors
        PANEL_HEIGHT=24
        FONT_FAMILY='DejaVu Sans'
        FONT_SIZE=11
        cat "$PANEL_FIFO" | panel_dzen2 -f "$FONT_FAMILY" -s "$FONT_SIZE" | dzen2 -h $PANEL_HEIGHT -dock -ta l -title-name panel -fn "${FONT_FAMILY}:pixelsize=${FONT_SIZE}" -fg "$COLOR_FOREGROUND" -bg "$COLOR_BACKGROUND"
        ;;
esac
